# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dw_containers_no_tabs.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        if not DockWidget.objectName():
            DockWidget.setObjectName(u"DockWidget")
        DockWidget.resize(416, 583)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout = QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frameDis_2 = QFrame(self.dockWidgetContents)
        self.frameDis_2.setObjectName(u"frameDis_2")
        self.frameDis_2.setEnabled(False)
        self.frameDis_2.setFrameShape(QFrame.StyledPanel)
        self.frameDis_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_40 = QGridLayout(self.frameDis_2)
        self.gridLayout_40.setObjectName(u"gridLayout_40")
        self.label_8 = QLabel(self.frameDis_2)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout_40.addWidget(self.label_8, 0, 0, 1, 1)


        self.gridLayout.addWidget(self.frameDis_2, 8, 3, 1, 2)

        self.widget_2 = QWidget(self.dockWidgetContents)
        self.widget_2.setObjectName(u"widget_2")
        self.gridLayout_39 = QGridLayout(self.widget_2)
        self.gridLayout_39.setObjectName(u"gridLayout_39")
        self.label_59 = QLabel(self.widget_2)
        self.label_59.setObjectName(u"label_59")

        self.gridLayout_39.addWidget(self.label_59, 0, 0, 1, 1)


        self.gridLayout.addWidget(self.widget_2, 9, 2, 1, 1)

        self.groupBox_2 = QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.gridLayout_7 = QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")

        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)


        self.gridLayout.addWidget(self.groupBox_2, 1, 2, 1, 1)

        self.frame_2 = QFrame(self.dockWidgetContents)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_43 = QGridLayout(self.frame_2)
        self.gridLayout_43.setObjectName(u"gridLayout_43")
        self.label_9 = QLabel(self.frame_2)
        self.label_9.setObjectName(u"label_9")

        self.gridLayout_43.addWidget(self.label_9, 0, 0, 1, 1)


        self.gridLayout.addWidget(self.frame_2, 8, 2, 1, 1)

        self.widgetDis_2 = QWidget(self.dockWidgetContents)
        self.widgetDis_2.setObjectName(u"widgetDis_2")
        self.widgetDis_2.setEnabled(False)
        self.gridLayout_44 = QGridLayout(self.widgetDis_2)
        self.gridLayout_44.setObjectName(u"gridLayout_44")
        self.label_125 = QLabel(self.widgetDis_2)
        self.label_125.setObjectName(u"label_125")

        self.gridLayout_44.addWidget(self.label_125, 0, 0, 1, 1)


        self.gridLayout.addWidget(self.widgetDis_2, 9, 3, 1, 2)

        self.groupBox_3 = QGroupBox(self.dockWidgetContents)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setCheckable(True)
        self.gridLayout_8 = QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.label_11 = QLabel(self.groupBox_3)
        self.label_11.setObjectName(u"label_11")

        self.gridLayout_8.addWidget(self.label_11, 0, 0, 1, 1)


        self.gridLayout.addWidget(self.groupBox_3, 2, 2, 1, 1)

        self.label_124 = QLabel(self.dockWidgetContents)
        self.label_124.setObjectName(u"label_124")
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_124.setFont(font)

        self.gridLayout.addWidget(self.label_124, 0, 2, 1, 1)

        self.label_126 = QLabel(self.dockWidgetContents)
        self.label_126.setObjectName(u"label_126")
        self.label_126.setFont(font)

        self.gridLayout.addWidget(self.label_126, 0, 3, 1, 2)

        self.label_127 = QLabel(self.dockWidgetContents)
        self.label_127.setObjectName(u"label_127")
        self.label_127.setFont(font)

        self.gridLayout.addWidget(self.label_127, 1, 0, 1, 1)

        self.label_128 = QLabel(self.dockWidgetContents)
        self.label_128.setObjectName(u"label_128")
        self.label_128.setFont(font)

        self.gridLayout.addWidget(self.label_128, 4, 0, 1, 1)

        self.scrollArea_2 = QScrollArea(self.dockWidgetContents)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 139, 192))
        self.verticalLayout_14 = QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.label_70 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_70.setObjectName(u"label_70")

        self.verticalLayout_14.addWidget(self.label_70)

        self.label_71 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_71.setObjectName(u"label_71")

        self.verticalLayout_14.addWidget(self.label_71)

        self.label_75 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_75.setObjectName(u"label_75")

        self.verticalLayout_14.addWidget(self.label_75)

        self.label_76 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_76.setObjectName(u"label_76")

        self.verticalLayout_14.addWidget(self.label_76)

        self.label_77 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_77.setObjectName(u"label_77")

        self.verticalLayout_14.addWidget(self.label_77)

        self.label_78 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_78.setObjectName(u"label_78")

        self.verticalLayout_14.addWidget(self.label_78)

        self.label_79 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_79.setObjectName(u"label_79")

        self.verticalLayout_14.addWidget(self.label_79)

        self.label_80 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_80.setObjectName(u"label_80")

        self.verticalLayout_14.addWidget(self.label_80)

        self.label_81 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_81.setObjectName(u"label_81")

        self.verticalLayout_14.addWidget(self.label_81)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.gridLayout.addWidget(self.scrollArea_2, 4, 2, 1, 1)

        self.scrollAreaDis_2 = QScrollArea(self.dockWidgetContents)
        self.scrollAreaDis_2.setObjectName(u"scrollAreaDis_2")
        self.scrollAreaDis_2.setEnabled(False)
        self.scrollAreaDis_2.setWidgetResizable(True)
        self.scrollAreaWidgetContentsDis_2 = QWidget()
        self.scrollAreaWidgetContentsDis_2.setObjectName(u"scrollAreaWidgetContentsDis_2")
        self.scrollAreaWidgetContentsDis_2.setGeometry(QRect(0, 0, 139, 192))
        self.verticalLayout_13 = QVBoxLayout(self.scrollAreaWidgetContentsDis_2)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.label_115 = QLabel(self.scrollAreaWidgetContentsDis_2)
        self.label_115.setObjectName(u"label_115")

        self.verticalLayout_13.addWidget(self.label_115)

        self.label_116 = QLabel(self.scrollAreaWidgetContentsDis_2)
        self.label_116.setObjectName(u"label_116")

        self.verticalLayout_13.addWidget(self.label_116)

        self.label_117 = QLabel(self.scrollAreaWidgetContentsDis_2)
        self.label_117.setObjectName(u"label_117")

        self.verticalLayout_13.addWidget(self.label_117)

        self.label_118 = QLabel(self.scrollAreaWidgetContentsDis_2)
        self.label_118.setObjectName(u"label_118")

        self.verticalLayout_13.addWidget(self.label_118)

        self.label_119 = QLabel(self.scrollAreaWidgetContentsDis_2)
        self.label_119.setObjectName(u"label_119")

        self.verticalLayout_13.addWidget(self.label_119)

        self.label_120 = QLabel(self.scrollAreaWidgetContentsDis_2)
        self.label_120.setObjectName(u"label_120")

        self.verticalLayout_13.addWidget(self.label_120)

        self.label_121 = QLabel(self.scrollAreaWidgetContentsDis_2)
        self.label_121.setObjectName(u"label_121")

        self.verticalLayout_13.addWidget(self.label_121)

        self.label_122 = QLabel(self.scrollAreaWidgetContentsDis_2)
        self.label_122.setObjectName(u"label_122")

        self.verticalLayout_13.addWidget(self.label_122)

        self.label_123 = QLabel(self.scrollAreaWidgetContentsDis_2)
        self.label_123.setObjectName(u"label_123")

        self.verticalLayout_13.addWidget(self.label_123)

        self.scrollAreaDis_2.setWidget(self.scrollAreaWidgetContentsDis_2)

        self.gridLayout.addWidget(self.scrollAreaDis_2, 4, 3, 1, 2)

        self.label_134 = QLabel(self.dockWidgetContents)
        self.label_134.setObjectName(u"label_134")
        self.label_134.setFont(font)

        self.gridLayout.addWidget(self.label_134, 2, 0, 1, 1)

        self.stackedWidget_2 = QStackedWidget(self.dockWidgetContents)
        self.stackedWidget_2.setObjectName(u"stackedWidget_2")
        self.page1_2 = QWidget()
        self.page1_2.setObjectName(u"page1_2")
        self.gridLayout_35 = QGridLayout(self.page1_2)
        self.gridLayout_35.setObjectName(u"gridLayout_35")
        self.label_57 = QLabel(self.page1_2)
        self.label_57.setObjectName(u"label_57")

        self.gridLayout_35.addWidget(self.label_57, 0, 0, 1, 1)

        self.stackedWidget_2.addWidget(self.page1_2)
        self.page2_2 = QWidget()
        self.page2_2.setObjectName(u"page2_2")
        self.gridLayout_36 = QGridLayout(self.page2_2)
        self.gridLayout_36.setObjectName(u"gridLayout_36")
        self.label_58 = QLabel(self.page2_2)
        self.label_58.setObjectName(u"label_58")

        self.gridLayout_36.addWidget(self.label_58, 0, 0, 1, 1)

        self.stackedWidget_2.addWidget(self.page2_2)

        self.gridLayout.addWidget(self.stackedWidget_2, 7, 2, 1, 1)

        self.toolBoxDis_2 = QToolBox(self.dockWidgetContents)
        self.toolBoxDis_2.setObjectName(u"toolBoxDis_2")
        self.toolBoxDis_2.setEnabled(False)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.page_6.setGeometry(QRect(0, 0, 160, 76))
        self.gridLayout_29 = QGridLayout(self.page_6)
        self.gridLayout_29.setObjectName(u"gridLayout_29")
        self.label_109 = QLabel(self.page_6)
        self.label_109.setObjectName(u"label_109")

        self.gridLayout_29.addWidget(self.label_109, 2, 0, 1, 1)

        self.toolBoxDis_2.addItem(self.page_6, u"Page 1")
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.page_7.setGeometry(QRect(0, 0, 140, 32))
        self.gridLayout_34 = QGridLayout(self.page_7)
        self.gridLayout_34.setObjectName(u"gridLayout_34")
        self.label_110 = QLabel(self.page_7)
        self.label_110.setObjectName(u"label_110")

        self.gridLayout_34.addWidget(self.label_110, 0, 0, 1, 1)

        self.toolBoxDis_2.addItem(self.page_7, u"Page 2")

        self.gridLayout.addWidget(self.toolBoxDis_2, 6, 3, 1, 2)

        self.label_133 = QLabel(self.dockWidgetContents)
        self.label_133.setObjectName(u"label_133")
        self.label_133.setFont(font)

        self.gridLayout.addWidget(self.label_133, 10, 0, 1, 1)

        self.stackedWidgetDis_2 = QStackedWidget(self.dockWidgetContents)
        self.stackedWidgetDis_2.setObjectName(u"stackedWidgetDis_2")
        self.stackedWidgetDis_2.setEnabled(False)
        self.page1Dis_2 = QWidget()
        self.page1Dis_2.setObjectName(u"page1Dis_2")
        self.gridLayout_37 = QGridLayout(self.page1Dis_2)
        self.gridLayout_37.setObjectName(u"gridLayout_37")
        self.label_113 = QLabel(self.page1Dis_2)
        self.label_113.setObjectName(u"label_113")

        self.gridLayout_37.addWidget(self.label_113, 0, 0, 1, 1)

        self.stackedWidgetDis_2.addWidget(self.page1Dis_2)
        self.page2Dis_2 = QWidget()
        self.page2Dis_2.setObjectName(u"page2Dis_2")
        self.gridLayout_38 = QGridLayout(self.page2Dis_2)
        self.gridLayout_38.setObjectName(u"gridLayout_38")
        self.label_114 = QLabel(self.page2Dis_2)
        self.label_114.setObjectName(u"label_114")

        self.gridLayout_38.addWidget(self.label_114, 0, 0, 1, 1)

        self.stackedWidgetDis_2.addWidget(self.page2Dis_2)

        self.gridLayout.addWidget(self.stackedWidgetDis_2, 7, 3, 1, 2)

        self.label_131 = QLabel(self.dockWidgetContents)
        self.label_131.setObjectName(u"label_131")
        self.label_131.setFont(font)

        self.gridLayout.addWidget(self.label_131, 8, 0, 1, 1)

        self.label_130 = QLabel(self.dockWidgetContents)
        self.label_130.setObjectName(u"label_130")
        self.label_130.setFont(font)

        self.gridLayout.addWidget(self.label_130, 7, 0, 1, 1)

        self.label_129 = QLabel(self.dockWidgetContents)
        self.label_129.setObjectName(u"label_129")
        self.label_129.setFont(font)

        self.gridLayout.addWidget(self.label_129, 6, 0, 1, 1)

        self.mdiArea_2 = QMdiArea(self.dockWidgetContents)
        self.mdiArea_2.setObjectName(u"mdiArea_2")
        self.subwindow1_2 = QWidget()
        self.subwindow1_2.setObjectName(u"subwindow1_2")
        self.verticalLayout_11 = QVBoxLayout(self.subwindow1_2)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.label_29 = QLabel(self.subwindow1_2)
        self.label_29.setObjectName(u"label_29")

        self.verticalLayout_11.addWidget(self.label_29)

        self.mdiArea_2.addSubWindow(self.subwindow1_2)
        self.subwindow2_2 = QWidget()
        self.subwindow2_2.setObjectName(u"subwindow2_2")
        self.verticalLayout_12 = QVBoxLayout(self.subwindow2_2)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.label_56 = QLabel(self.subwindow2_2)
        self.label_56.setObjectName(u"label_56")

        self.verticalLayout_12.addWidget(self.label_56)

        self.mdiArea_2.addSubWindow(self.subwindow2_2)

        self.gridLayout.addWidget(self.mdiArea_2, 10, 2, 1, 1)

        self.toolBox_2 = QToolBox(self.dockWidgetContents)
        self.toolBox_2.setObjectName(u"toolBox_2")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setGeometry(QRect(0, 0, 160, 76))
        self.gridLayout_41 = QGridLayout(self.page_3)
        self.gridLayout_41.setObjectName(u"gridLayout_41")
        self.label_60 = QLabel(self.page_3)
        self.label_60.setObjectName(u"label_60")

        self.gridLayout_41.addWidget(self.label_60, 2, 0, 1, 1)

        self.toolBox_2.addItem(self.page_3, u"Page 1")
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.page_8.setGeometry(QRect(0, 0, 140, 32))
        self.gridLayout_42 = QGridLayout(self.page_8)
        self.gridLayout_42.setObjectName(u"gridLayout_42")
        self.label_61 = QLabel(self.page_8)
        self.label_61.setObjectName(u"label_61")

        self.gridLayout_42.addWidget(self.label_61, 0, 0, 1, 1)

        self.toolBox_2.addItem(self.page_8, u"Page 2")

        self.gridLayout.addWidget(self.toolBox_2, 6, 2, 1, 1)

        self.label_132 = QLabel(self.dockWidgetContents)
        self.label_132.setObjectName(u"label_132")
        self.label_132.setFont(font)

        self.gridLayout.addWidget(self.label_132, 9, 0, 1, 1)

        self.mdiAreaDis_2 = QMdiArea(self.dockWidgetContents)
        self.mdiAreaDis_2.setObjectName(u"mdiAreaDis_2")
        self.mdiAreaDis_2.setEnabled(False)
        self.subwindow1Dis_2 = QWidget()
        self.subwindow1Dis_2.setObjectName(u"subwindow1Dis_2")
        self.verticalLayout_9 = QVBoxLayout(self.subwindow1Dis_2)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.label_111 = QLabel(self.subwindow1Dis_2)
        self.label_111.setObjectName(u"label_111")

        self.verticalLayout_9.addWidget(self.label_111)

        self.mdiAreaDis_2.addSubWindow(self.subwindow1Dis_2)
        self.subwindow2Dis_2 = QWidget()
        self.subwindow2Dis_2.setObjectName(u"subwindow2Dis_2")
        self.verticalLayout_10 = QVBoxLayout(self.subwindow2Dis_2)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.label_112 = QLabel(self.subwindow2Dis_2)
        self.label_112.setObjectName(u"label_112")

        self.verticalLayout_10.addWidget(self.label_112)

        self.mdiAreaDis_2.addSubWindow(self.subwindow2Dis_2)

        self.gridLayout.addWidget(self.mdiAreaDis_2, 10, 3, 1, 2)

        self.groupBoxDis_3 = QGroupBox(self.dockWidgetContents)
        self.groupBoxDis_3.setObjectName(u"groupBoxDis_3")
        self.groupBoxDis_3.setEnabled(False)
        self.groupBoxDis_3.setCheckable(True)
        self.verticalLayout_5 = QVBoxLayout(self.groupBoxDis_3)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.label_12 = QLabel(self.groupBoxDis_3)
        self.label_12.setObjectName(u"label_12")

        self.verticalLayout_5.addWidget(self.label_12)


        self.gridLayout.addWidget(self.groupBoxDis_3, 2, 3, 1, 2)

        self.groupBoxDis_2 = QGroupBox(self.dockWidgetContents)
        self.groupBoxDis_2.setObjectName(u"groupBoxDis_2")
        self.groupBoxDis_2.setEnabled(False)
        self.verticalLayout_4 = QVBoxLayout(self.groupBoxDis_2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.label_7 = QLabel(self.groupBoxDis_2)
        self.label_7.setObjectName(u"label_7")

        self.verticalLayout_4.addWidget(self.label_7)


        self.gridLayout.addWidget(self.groupBoxDis_2, 1, 3, 1, 2)

        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)

        self.stackedWidget_2.setCurrentIndex(1)
        self.toolBoxDis_2.setCurrentIndex(0)
        self.stackedWidgetDis_2.setCurrentIndex(1)
        self.toolBox_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(DockWidget)
    # setupUi

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QCoreApplication.translate("DockWidget", u"Containers - No Tabs", None))
#if QT_CONFIG(tooltip)
        self.frameDis_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.frameDis_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.frameDis_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_8.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_8.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_8.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_8.setText(QCoreApplication.translate("DockWidget", u"Inside Frame", None))
#if QT_CONFIG(tooltip)
        self.widget_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.widget_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.widget_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_59.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_59.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_59.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_59.setText(QCoreApplication.translate("DockWidget", u"Inside Widget", None))
#if QT_CONFIG(tooltip)
        self.groupBox_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.groupBox_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.groupBox_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.groupBox_2.setTitle(QCoreApplication.translate("DockWidget", u"GroupBox", None))
#if QT_CONFIG(tooltip)
        self.label_10.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_10.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_10.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_10.setText(QCoreApplication.translate("DockWidget", u"Inside GroupBox", None))
#if QT_CONFIG(tooltip)
        self.frame_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.frame_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.frame_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_9.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_9.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_9.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_9.setText(QCoreApplication.translate("DockWidget", u"Inside Frame", None))
#if QT_CONFIG(tooltip)
        self.widgetDis_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.widgetDis_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.widgetDis_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_125.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_125.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_125.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_125.setText(QCoreApplication.translate("DockWidget", u"Inside Widget", None))
#if QT_CONFIG(tooltip)
        self.groupBox_3.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.groupBox_3.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.groupBox_3.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.groupBox_3.setTitle(QCoreApplication.translate("DockWidget", u"GroupBox Checkable", None))
#if QT_CONFIG(tooltip)
        self.label_11.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_11.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_11.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_11.setText(QCoreApplication.translate("DockWidget", u"Inside GroupBox", None))
        self.label_124.setText(QCoreApplication.translate("DockWidget", u"Enabled", None))
        self.label_126.setText(QCoreApplication.translate("DockWidget", u"Disabled", None))
        self.label_127.setText(QCoreApplication.translate("DockWidget", u"GroupBox", None))
        self.label_128.setText(QCoreApplication.translate("DockWidget", u"ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.scrollArea_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.scrollArea_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.scrollArea_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_70.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_70.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_70.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_70.setText(QCoreApplication.translate("DockWidget", u"Inside ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_71.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_71.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_71.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_71.setText(QCoreApplication.translate("DockWidget", u"ScroolArea ", None))
#if QT_CONFIG(tooltip)
        self.label_75.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_75.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_75.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_75.setText(QCoreApplication.translate("DockWidget", u"Inside ScroolArea ", None))
#if QT_CONFIG(tooltip)
        self.label_76.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_76.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_76.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_76.setText(QCoreApplication.translate("DockWidget", u"ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_77.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_77.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_77.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_77.setText(QCoreApplication.translate("DockWidget", u"Inside ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_78.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_78.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_78.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_78.setText(QCoreApplication.translate("DockWidget", u"ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_79.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_79.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_79.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_79.setText(QCoreApplication.translate("DockWidget", u"Inside ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_80.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_80.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_80.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_80.setText(QCoreApplication.translate("DockWidget", u"ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_81.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_81.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_81.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_81.setText(QCoreApplication.translate("DockWidget", u"Inside ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.scrollAreaDis_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.scrollAreaDis_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.scrollAreaDis_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_115.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_115.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_115.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_115.setText(QCoreApplication.translate("DockWidget", u"Inside ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_116.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_116.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_116.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_116.setText(QCoreApplication.translate("DockWidget", u"ScroolArea ", None))
#if QT_CONFIG(tooltip)
        self.label_117.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_117.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_117.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_117.setText(QCoreApplication.translate("DockWidget", u"Inside ScroolArea ", None))
#if QT_CONFIG(tooltip)
        self.label_118.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_118.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_118.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_118.setText(QCoreApplication.translate("DockWidget", u"ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_119.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_119.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_119.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_119.setText(QCoreApplication.translate("DockWidget", u"Inside ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_120.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_120.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_120.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_120.setText(QCoreApplication.translate("DockWidget", u"ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_121.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_121.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_121.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_121.setText(QCoreApplication.translate("DockWidget", u"Inside ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_122.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_122.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_122.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_122.setText(QCoreApplication.translate("DockWidget", u"ScroolArea", None))
#if QT_CONFIG(tooltip)
        self.label_123.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_123.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_123.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_123.setText(QCoreApplication.translate("DockWidget", u"Inside ScroolArea", None))
        self.label_134.setText(QCoreApplication.translate("DockWidget", u"GroupBox", None))
#if QT_CONFIG(tooltip)
        self.stackedWidget_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.stackedWidget_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.stackedWidget_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_57.setText(QCoreApplication.translate("DockWidget", u"Inside Stacked Page 1", None))
#if QT_CONFIG(tooltip)
        self.label_58.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_58.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_58.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_58.setText(QCoreApplication.translate("DockWidget", u"Inside Stacked Page 2", None))
#if QT_CONFIG(tooltip)
        self.toolBoxDis_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.toolBoxDis_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.toolBoxDis_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_109.setText(QCoreApplication.translate("DockWidget", u"Inside ToolBox Page 1", None))
        self.toolBoxDis_2.setItemText(self.toolBoxDis_2.indexOf(self.page_6), QCoreApplication.translate("DockWidget", u"Page 1", None))
#if QT_CONFIG(tooltip)
        self.label_110.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_110.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_110.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_110.setText(QCoreApplication.translate("DockWidget", u"Inside ToolBox Page 2", None))
        self.toolBoxDis_2.setItemText(self.toolBoxDis_2.indexOf(self.page_7), QCoreApplication.translate("DockWidget", u"Page 2", None))
        self.label_133.setText(QCoreApplication.translate("DockWidget", u"MDI Area", None))
#if QT_CONFIG(tooltip)
        self.stackedWidgetDis_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.stackedWidgetDis_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.stackedWidgetDis_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_113.setText(QCoreApplication.translate("DockWidget", u"Inside Stacked Page 1", None))
#if QT_CONFIG(tooltip)
        self.label_114.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_114.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_114.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_114.setText(QCoreApplication.translate("DockWidget", u"Inside Stacked Page 2", None))
        self.label_131.setText(QCoreApplication.translate("DockWidget", u"Frame", None))
        self.label_130.setText(QCoreApplication.translate("DockWidget", u"Stacked", None))
        self.label_129.setText(QCoreApplication.translate("DockWidget", u"ToolBox", None))
        self.subwindow1_2.setWindowTitle(QCoreApplication.translate("DockWidget", u"Subwindow", None))
        self.label_29.setText(QCoreApplication.translate("DockWidget", u"Inside MDI Area 1", None))
        self.subwindow2_2.setWindowTitle(QCoreApplication.translate("DockWidget", u"Subwindow", None))
        self.label_56.setText(QCoreApplication.translate("DockWidget", u"Inside MDI Area 2 ", None))
#if QT_CONFIG(tooltip)
        self.toolBox_2.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.toolBox_2.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.toolBox_2.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_60.setText(QCoreApplication.translate("DockWidget", u"Inside ToolBox Page 1", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_3), QCoreApplication.translate("DockWidget", u"Page 1", None))
#if QT_CONFIG(tooltip)
        self.label_61.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_61.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_61.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_61.setText(QCoreApplication.translate("DockWidget", u"Inside ToolBox Page 2", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_8), QCoreApplication.translate("DockWidget", u"Page 2", None))
        self.label_132.setText(QCoreApplication.translate("DockWidget", u"Widget", None))
        self.subwindow1Dis_2.setWindowTitle(QCoreApplication.translate("DockWidget", u"Subwindow", None))
        self.label_111.setText(QCoreApplication.translate("DockWidget", u"Inside MDI Area 1", None))
        self.subwindow2Dis_2.setWindowTitle(QCoreApplication.translate("DockWidget", u"Subwindow", None))
        self.label_112.setText(QCoreApplication.translate("DockWidget", u"Inside MDI Area 2 ", None))
        self.groupBoxDis_3.setTitle(QCoreApplication.translate("DockWidget", u"GroupBox Checkeable", None))
        self.label_12.setText(QCoreApplication.translate("DockWidget", u"Inside GroupBox", None))
        self.groupBoxDis_2.setTitle(QCoreApplication.translate("DockWidget", u"GroupBox", None))
        self.label_7.setText(QCoreApplication.translate("DockWidget", u"Inside GroupBox", None))
    # retranslateUi

