# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dw_inputs_fields.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import style_rc

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        if not DockWidget.objectName():
            DockWidget.setObjectName(u"DockWidget")
        DockWidget.resize(703, 557)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout = QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label = QLabel(self.dockWidgetContents)
        self.label.setObjectName(u"label")
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)

        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)

        self.label_2 = QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font)

        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)

        self.label_12 = QLabel(self.dockWidgetContents)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setMinimumSize(QSize(0, 0))
        self.label_12.setMaximumSize(QSize(16777215, 16777215))
        self.label_12.setFont(font)

        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)

        self.fontComboBox = QFontComboBox(self.dockWidgetContents)
        self.fontComboBox.setObjectName(u"fontComboBox")
        self.fontComboBox.setMinimumSize(QSize(0, 0))
        self.fontComboBox.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.fontComboBox, 1, 1, 1, 1)

        self.fontComboBoxDis = QFontComboBox(self.dockWidgetContents)
        self.fontComboBoxDis.setObjectName(u"fontComboBoxDis")
        self.fontComboBoxDis.setEnabled(False)
        self.fontComboBoxDis.setMinimumSize(QSize(0, 0))
        self.fontComboBoxDis.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.fontComboBoxDis, 1, 2, 1, 1)

        self.label_3 = QLabel(self.dockWidgetContents)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)

        self.comboBoxEdit = QComboBox(self.dockWidgetContents)
        self.comboBoxEdit.addItem("")
        self.comboBoxEdit.addItem("")
        self.comboBoxEdit.addItem("")
        icon = QIcon()
        icon.addFile(u":/qss_icons/dark/rc/window_undock_focus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.comboBoxEdit.addItem(icon, "")
        icon1 = QIcon()
        icon1.addFile(u":/qss_icons/dark/rc/window_close_focus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.comboBoxEdit.addItem(icon1, "")
        self.comboBoxEdit.setObjectName(u"comboBoxEdit")
        self.comboBoxEdit.setEditable(True)

        self.gridLayout.addWidget(self.comboBoxEdit, 2, 1, 1, 1)

        self.comboBoxEditDis = QComboBox(self.dockWidgetContents)
        self.comboBoxEditDis.addItem("")
        self.comboBoxEditDis.addItem("")
        self.comboBoxEditDis.addItem("")
        self.comboBoxEditDis.setObjectName(u"comboBoxEditDis")
        self.comboBoxEditDis.setEnabled(False)
        self.comboBoxEditDis.setEditable(True)

        self.gridLayout.addWidget(self.comboBoxEditDis, 2, 2, 1, 1)

        self.label_13 = QLabel(self.dockWidgetContents)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setMinimumSize(QSize(0, 0))
        self.label_13.setMaximumSize(QSize(16777215, 16777215))
        self.label_13.setFont(font)

        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)

        self.lineEdit = QLineEdit(self.dockWidgetContents)
        self.lineEdit.setObjectName(u"lineEdit")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QSize(0, 0))
        self.lineEdit.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 1)

        self.lineEditDis = QLineEdit(self.dockWidgetContents)
        self.lineEditDis.setObjectName(u"lineEditDis")
        self.lineEditDis.setEnabled(False)
        sizePolicy.setHeightForWidth(self.lineEditDis.sizePolicy().hasHeightForWidth())
        self.lineEditDis.setSizePolicy(sizePolicy)
        self.lineEditDis.setMinimumSize(QSize(0, 0))
        self.lineEditDis.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.lineEditDis, 3, 2, 1, 1)

        self.label_14 = QLabel(self.dockWidgetContents)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setMinimumSize(QSize(0, 0))
        self.label_14.setMaximumSize(QSize(16777215, 16777215))
        self.label_14.setFont(font)

        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)

        self.textEdit = QTextEdit(self.dockWidgetContents)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setMinimumSize(QSize(0, 0))
        self.textEdit.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.textEdit, 4, 1, 1, 1)

        self.textEditDis = QTextEdit(self.dockWidgetContents)
        self.textEditDis.setObjectName(u"textEditDis")
        self.textEditDis.setEnabled(False)
        self.textEditDis.setMinimumSize(QSize(0, 0))
        self.textEditDis.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.textEditDis, 4, 2, 1, 1)

        self.label_15 = QLabel(self.dockWidgetContents)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setMinimumSize(QSize(0, 0))
        self.label_15.setMaximumSize(QSize(16777215, 16777215))
        self.label_15.setFont(font)

        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)

        self.plainTextEdit = QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setMinimumSize(QSize(0, 0))
        self.plainTextEdit.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.plainTextEdit, 5, 1, 1, 1)

        self.plainTextEditDis = QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEditDis.setObjectName(u"plainTextEditDis")
        self.plainTextEditDis.setEnabled(False)
        self.plainTextEditDis.setMinimumSize(QSize(0, 0))
        self.plainTextEditDis.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.plainTextEditDis, 5, 2, 1, 1)

        self.label_16 = QLabel(self.dockWidgetContents)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setMinimumSize(QSize(0, 0))
        self.label_16.setMaximumSize(QSize(16777215, 16777215))
        self.label_16.setFont(font)

        self.gridLayout.addWidget(self.label_16, 6, 0, 1, 1)

        self.spinBox = QSpinBox(self.dockWidgetContents)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setMinimumSize(QSize(0, 0))
        self.spinBox.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.spinBox, 6, 1, 1, 1)

        self.spinBoxDis = QSpinBox(self.dockWidgetContents)
        self.spinBoxDis.setObjectName(u"spinBoxDis")
        self.spinBoxDis.setEnabled(False)
        self.spinBoxDis.setMinimumSize(QSize(0, 0))
        self.spinBoxDis.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.spinBoxDis, 6, 2, 1, 1)

        self.label_17 = QLabel(self.dockWidgetContents)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setMinimumSize(QSize(0, 0))
        self.label_17.setMaximumSize(QSize(16777215, 16777215))
        self.label_17.setFont(font)

        self.gridLayout.addWidget(self.label_17, 7, 0, 1, 1)

        self.doubleSpinBox = QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setMinimumSize(QSize(0, 0))
        self.doubleSpinBox.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.doubleSpinBox, 7, 1, 1, 1)

        self.doubleSpinBoxDis = QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxDis.setObjectName(u"doubleSpinBoxDis")
        self.doubleSpinBoxDis.setEnabled(False)
        self.doubleSpinBoxDis.setMinimumSize(QSize(0, 0))
        self.doubleSpinBoxDis.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.doubleSpinBoxDis, 7, 2, 1, 1)

        self.label_18 = QLabel(self.dockWidgetContents)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setMinimumSize(QSize(0, 0))
        self.label_18.setMaximumSize(QSize(16777215, 16777215))
        self.label_18.setFont(font)

        self.gridLayout.addWidget(self.label_18, 8, 0, 1, 1)

        self.timeEdit = QTimeEdit(self.dockWidgetContents)
        self.timeEdit.setObjectName(u"timeEdit")
        self.timeEdit.setMinimumSize(QSize(0, 0))
        self.timeEdit.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.timeEdit, 8, 1, 1, 1)

        self.timeEditDis = QTimeEdit(self.dockWidgetContents)
        self.timeEditDis.setObjectName(u"timeEditDis")
        self.timeEditDis.setEnabled(False)
        self.timeEditDis.setMinimumSize(QSize(0, 0))
        self.timeEditDis.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.timeEditDis, 8, 2, 1, 1)

        self.label_19 = QLabel(self.dockWidgetContents)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setMinimumSize(QSize(0, 0))
        self.label_19.setMaximumSize(QSize(16777215, 16777215))
        self.label_19.setFont(font)

        self.gridLayout.addWidget(self.label_19, 9, 0, 1, 1)

        self.dateEdit = QDateEdit(self.dockWidgetContents)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setMinimumSize(QSize(0, 0))
        self.dateEdit.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.dateEdit, 9, 1, 1, 1)

        self.dateEditDis = QDateEdit(self.dockWidgetContents)
        self.dateEditDis.setObjectName(u"dateEditDis")
        self.dateEditDis.setEnabled(False)
        self.dateEditDis.setMinimumSize(QSize(0, 0))
        self.dateEditDis.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.dateEditDis, 9, 2, 1, 1)

        self.label_20 = QLabel(self.dockWidgetContents)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setMinimumSize(QSize(0, 0))
        self.label_20.setMaximumSize(QSize(16777215, 16777215))
        self.label_20.setFont(font)

        self.gridLayout.addWidget(self.label_20, 10, 0, 1, 1)

        self.dateTimeEdit = QDateTimeEdit(self.dockWidgetContents)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setMinimumSize(QSize(0, 0))
        self.dateTimeEdit.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.dateTimeEdit, 10, 1, 1, 1)

        self.dateTimeEditDis = QDateTimeEdit(self.dockWidgetContents)
        self.dateTimeEditDis.setObjectName(u"dateTimeEditDis")
        self.dateTimeEditDis.setEnabled(False)
        self.dateTimeEditDis.setMinimumSize(QSize(0, 0))
        self.dateTimeEditDis.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.dateTimeEditDis, 10, 2, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout.addItem(self.verticalSpacer, 11, 0, 1, 1)

        self.label_51 = QLabel(self.dockWidgetContents)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_51, 12, 0, 1, 3)

        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.fontComboBox.editTextChanged.connect(self.fontComboBoxDis.setEditText)
        self.lineEdit.textEdited.connect(self.lineEditDis.setText)
        self.spinBox.valueChanged.connect(self.spinBoxDis.setValue)
        self.doubleSpinBox.valueChanged.connect(self.doubleSpinBoxDis.setValue)
        self.timeEdit.timeChanged.connect(self.timeEditDis.setTime)
        self.dateEdit.dateTimeChanged.connect(self.dateEditDis.setDateTime)
        self.dateTimeEdit.dateTimeChanged.connect(self.dateTimeEditDis.setDateTime)

        QMetaObject.connectSlotsByName(DockWidget)
    # setupUi

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QCoreApplication.translate("DockWidget", u"Inputs - Fields", None))
        self.label.setText(QCoreApplication.translate("DockWidget", u"Enabled", None))
        self.label_2.setText(QCoreApplication.translate("DockWidget", u"Disabled", None))
#if QT_CONFIG(tooltip)
        self.label_12.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_12.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_12.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_12.setText(QCoreApplication.translate("DockWidget", u"FontComboBox", None))
#if QT_CONFIG(tooltip)
        self.fontComboBox.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.fontComboBox.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.fontComboBox.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.fontComboBoxDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.fontComboBoxDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.fontComboBoxDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_3.setText(QCoreApplication.translate("DockWidget", u"<html><head/><body><p><span style=\" font-weight:600;\">ComboBox</span></p></body></html>", None))
        self.comboBoxEdit.setItemText(0, QCoreApplication.translate("DockWidget", u"ComboBoxEditable", None))
        self.comboBoxEdit.setItemText(1, QCoreApplication.translate("DockWidget", u"Option 1 No Icon", None))
        self.comboBoxEdit.setItemText(2, QCoreApplication.translate("DockWidget", u"Option 2 No Icon", None))
        self.comboBoxEdit.setItemText(3, QCoreApplication.translate("DockWidget", u"Option 1 With Icon", None))
        self.comboBoxEdit.setItemText(4, QCoreApplication.translate("DockWidget", u"Option 2 With Icon", None))

        self.comboBoxEditDis.setItemText(0, QCoreApplication.translate("DockWidget", u"ComboBoxEditable", None))
        self.comboBoxEditDis.setItemText(1, QCoreApplication.translate("DockWidget", u"Second option", None))
        self.comboBoxEditDis.setItemText(2, "")

#if QT_CONFIG(tooltip)
        self.label_13.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_13.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_13.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_13.setText(QCoreApplication.translate("DockWidget", u"LineEdit", None))
#if QT_CONFIG(tooltip)
        self.lineEdit.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.lineEdit.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.lineEdit.setText(QCoreApplication.translate("DockWidget", u"LineEdit", None))
#if QT_CONFIG(tooltip)
        self.lineEditDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEditDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.lineEditDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.lineEditDis.setText(QCoreApplication.translate("DockWidget", u"LineEdit", None))
#if QT_CONFIG(tooltip)
        self.label_14.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_14.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_14.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_14.setText(QCoreApplication.translate("DockWidget", u"TextEdit", None))
#if QT_CONFIG(tooltip)
        self.textEdit.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.textEdit.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.textEdit.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.textEdit.setHtml(QCoreApplication.translate("DockWidget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.15094pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Cantarell'; font-size:11pt;\">TextEdit</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.textEditDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.textEditDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.textEditDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.textEditDis.setHtml(QCoreApplication.translate("DockWidget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.15094pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Cantarell'; font-size:11pt;\">TextEdit</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_15.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_15.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_15.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_15.setText(QCoreApplication.translate("DockWidget", u"PlainTextEdit", None))
#if QT_CONFIG(tooltip)
        self.plainTextEdit.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.plainTextEdit.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.plainTextEdit.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.plainTextEdit.setPlainText(QCoreApplication.translate("DockWidget", u"PlainTextEdit", None))
#if QT_CONFIG(tooltip)
        self.plainTextEditDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.plainTextEditDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.plainTextEditDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.plainTextEditDis.setPlainText(QCoreApplication.translate("DockWidget", u"PlainTextEdit", None))
#if QT_CONFIG(tooltip)
        self.label_16.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_16.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_16.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_16.setText(QCoreApplication.translate("DockWidget", u"SpinBox", None))
#if QT_CONFIG(tooltip)
        self.spinBox.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.spinBox.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.spinBox.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.spinBoxDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.spinBoxDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.spinBoxDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_17.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_17.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_17.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_17.setText(QCoreApplication.translate("DockWidget", u"DoubleSpinBox", None))
#if QT_CONFIG(tooltip)
        self.doubleSpinBox.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.doubleSpinBox.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.doubleSpinBox.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.doubleSpinBoxDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.doubleSpinBoxDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.doubleSpinBoxDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_18.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_18.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_18.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_18.setText(QCoreApplication.translate("DockWidget", u"TimeEdit", None))
#if QT_CONFIG(tooltip)
        self.timeEdit.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.timeEdit.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.timeEdit.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.timeEditDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.timeEditDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.timeEditDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_19.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_19.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_19.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_19.setText(QCoreApplication.translate("DockWidget", u"DateEdit", None))
#if QT_CONFIG(tooltip)
        self.dateEdit.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dateEdit.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.dateEdit.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.dateEditDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dateEditDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.dateEditDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_20.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_20.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_20.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_20.setText(QCoreApplication.translate("DockWidget", u"TimeDateEdit", None))
#if QT_CONFIG(tooltip)
        self.dateTimeEdit.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dateTimeEdit.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.dateTimeEdit.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.dateTimeEditDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dateTimeEditDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.dateTimeEditDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_51.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_51.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_51.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_51.setText(QCoreApplication.translate("DockWidget", u"Inside DockWidget", None))
    # retranslateUi

