# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dw_inputs_no_fields.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import style_rc

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        if not DockWidget.objectName():
            DockWidget.setObjectName(u"DockWidget")
        DockWidget.resize(455, 377)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout = QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(u"gridLayout")
        self.dial = QDial(self.dockWidgetContents)
        self.dial.setObjectName(u"dial")
        self.dial.setMinimumSize(QSize(0, 0))
        self.dial.setMaximumSize(QSize(16777215, 16777215))
        self.dial.setValue(50)

        self.gridLayout.addWidget(self.dial, 2, 1, 1, 1)

        self.label_25 = QLabel(self.dockWidgetContents)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setMinimumSize(QSize(0, 0))
        self.label_25.setMaximumSize(QSize(16777215, 16777215))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)

        self.gridLayout.addWidget(self.label_25, 7, 0, 1, 1)

        self.horizontalScrollBarDis = QScrollBar(self.dockWidgetContents)
        self.horizontalScrollBarDis.setObjectName(u"horizontalScrollBarDis")
        self.horizontalScrollBarDis.setEnabled(False)
        self.horizontalScrollBarDis.setMinimumSize(QSize(0, 0))
        self.horizontalScrollBarDis.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalScrollBarDis.setValue(50)
        self.horizontalScrollBarDis.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.horizontalScrollBarDis, 3, 2, 1, 1)

        self.verticalSlider = QSlider(self.dockWidgetContents)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setMinimumSize(QSize(0, 70))
        self.verticalSlider.setMaximumSize(QSize(16777215, 70))
        self.verticalSlider.setValue(50)
        self.verticalSlider.setOrientation(Qt.Vertical)

        self.gridLayout.addWidget(self.verticalSlider, 7, 1, 1, 1)

        self.label_24 = QLabel(self.dockWidgetContents)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setMinimumSize(QSize(0, 0))
        self.label_24.setMaximumSize(QSize(16777215, 16777215))
        self.label_24.setFont(font)

        self.gridLayout.addWidget(self.label_24, 4, 0, 1, 1)

        self.horizontalSlider = QSlider(self.dockWidgetContents)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setMinimumSize(QSize(0, 0))
        self.horizontalSlider.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalSlider.setValue(50)
        self.horizontalSlider.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.horizontalSlider, 4, 1, 2, 1)

        self.horizontalSliderDis = QSlider(self.dockWidgetContents)
        self.horizontalSliderDis.setObjectName(u"horizontalSliderDis")
        self.horizontalSliderDis.setEnabled(False)
        self.horizontalSliderDis.setMinimumSize(QSize(0, 0))
        self.horizontalSliderDis.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalSliderDis.setValue(50)
        self.horizontalSliderDis.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.horizontalSliderDis, 4, 2, 1, 1)

        self.label_23 = QLabel(self.dockWidgetContents)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setMinimumSize(QSize(0, 0))
        self.label_23.setMaximumSize(QSize(16777215, 16777215))
        self.label_23.setFont(font)

        self.gridLayout.addWidget(self.label_23, 6, 0, 1, 1)

        self.label_2 = QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font)

        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)

        self.verticalScrollBarDis = QScrollBar(self.dockWidgetContents)
        self.verticalScrollBarDis.setObjectName(u"verticalScrollBarDis")
        self.verticalScrollBarDis.setEnabled(False)
        self.verticalScrollBarDis.setMinimumSize(QSize(0, 70))
        self.verticalScrollBarDis.setMaximumSize(QSize(16777215, 70))
        self.verticalScrollBarDis.setValue(50)
        self.verticalScrollBarDis.setOrientation(Qt.Vertical)

        self.gridLayout.addWidget(self.verticalScrollBarDis, 5, 2, 2, 1)

        self.label_21 = QLabel(self.dockWidgetContents)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setMinimumSize(QSize(0, 0))
        self.label_21.setMaximumSize(QSize(16777215, 16777215))
        self.label_21.setFont(font)

        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)

        self.verticalSpacerDis = QSpacerItem(20, 0, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout.addItem(self.verticalSpacerDis, 8, 0, 1, 1)

        self.verticalScrollBar = QScrollBar(self.dockWidgetContents)
        self.verticalScrollBar.setObjectName(u"verticalScrollBar")
        self.verticalScrollBar.setMinimumSize(QSize(0, 70))
        self.verticalScrollBar.setMaximumSize(QSize(16777215, 70))
        self.verticalScrollBar.setValue(50)
        self.verticalScrollBar.setOrientation(Qt.Vertical)

        self.gridLayout.addWidget(self.verticalScrollBar, 6, 1, 1, 1)

        self.horizontalScrollBar = QScrollBar(self.dockWidgetContents)
        self.horizontalScrollBar.setObjectName(u"horizontalScrollBar")
        self.horizontalScrollBar.setMinimumSize(QSize(0, 0))
        self.horizontalScrollBar.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalScrollBar.setValue(50)
        self.horizontalScrollBar.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.horizontalScrollBar, 3, 1, 1, 1)

        self.comboBox = QComboBox(self.dockWidgetContents)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        icon = QIcon()
        icon.addFile(u":/qss_icons/dark/rc/window_undock_focus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.comboBox.addItem(icon, "")
        icon1 = QIcon()
        icon1.addFile(u":/qss_icons/dark/rc/window_close_focus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.comboBox.addItem(icon1, "")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setMinimumSize(QSize(0, 0))
        self.comboBox.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)

        self.label_22 = QLabel(self.dockWidgetContents)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setMinimumSize(QSize(0, 0))
        self.label_22.setMaximumSize(QSize(16777215, 16777215))
        self.label_22.setFont(font)

        self.gridLayout.addWidget(self.label_22, 3, 0, 1, 1)

        self.label = QLabel(self.dockWidgetContents)
        self.label.setObjectName(u"label")
        self.label.setFont(font)

        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)

        self.label_50 = QLabel(self.dockWidgetContents)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_50, 9, 0, 1, 3)

        self.label_11 = QLabel(self.dockWidgetContents)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setMinimumSize(QSize(0, 0))
        self.label_11.setMaximumSize(QSize(16777215, 16777215))
        self.label_11.setFont(font)

        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)

        self.dialDis = QDial(self.dockWidgetContents)
        self.dialDis.setObjectName(u"dialDis")
        self.dialDis.setEnabled(False)
        self.dialDis.setMinimumSize(QSize(0, 0))
        self.dialDis.setMaximumSize(QSize(16777215, 16777215))
        self.dialDis.setValue(50)

        self.gridLayout.addWidget(self.dialDis, 2, 2, 1, 1)

        self.verticalSliderDis = QSlider(self.dockWidgetContents)
        self.verticalSliderDis.setObjectName(u"verticalSliderDis")
        self.verticalSliderDis.setEnabled(False)
        self.verticalSliderDis.setMinimumSize(QSize(0, 70))
        self.verticalSliderDis.setMaximumSize(QSize(16777215, 70))
        self.verticalSliderDis.setValue(50)
        self.verticalSliderDis.setOrientation(Qt.Vertical)

        self.gridLayout.addWidget(self.verticalSliderDis, 7, 2, 1, 1)

        self.comboBoxDis = QComboBox(self.dockWidgetContents)
        self.comboBoxDis.addItem("")
        self.comboBoxDis.addItem("")
        self.comboBoxDis.addItem("")
        self.comboBoxDis.setObjectName(u"comboBoxDis")
        self.comboBoxDis.setEnabled(False)
        self.comboBoxDis.setMinimumSize(QSize(0, 0))
        self.comboBoxDis.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout.addWidget(self.comboBoxDis, 1, 2, 1, 1)

        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.dial.sliderMoved.connect(self.dialDis.setValue)
        self.horizontalScrollBar.sliderMoved.connect(self.horizontalScrollBarDis.setValue)
        self.horizontalSlider.sliderMoved.connect(self.horizontalSliderDis.setValue)
        self.verticalScrollBar.sliderMoved.connect(self.verticalScrollBarDis.setValue)
        self.verticalSlider.sliderMoved.connect(self.verticalSliderDis.setValue)
        self.comboBox.currentIndexChanged.connect(self.comboBoxDis.setCurrentIndex)

        QMetaObject.connectSlotsByName(DockWidget)
    # setupUi

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QCoreApplication.translate("DockWidget", u"Inputs - No Fields", None))
#if QT_CONFIG(tooltip)
        self.dial.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dial.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.dial.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_25.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_25.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_25.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_25.setText(QCoreApplication.translate("DockWidget", u"VerticalSlider", None))
#if QT_CONFIG(tooltip)
        self.horizontalScrollBarDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.horizontalScrollBarDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.horizontalScrollBarDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.verticalSlider.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.verticalSlider.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.verticalSlider.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_24.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_24.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_24.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_24.setText(QCoreApplication.translate("DockWidget", u"HorizontalSlider", None))
#if QT_CONFIG(tooltip)
        self.horizontalSlider.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.horizontalSlider.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.horizontalSlider.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.horizontalSliderDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.horizontalSliderDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.horizontalSliderDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_23.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_23.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_23.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_23.setText(QCoreApplication.translate("DockWidget", u"VerticalScroolBar", None))
        self.label_2.setText(QCoreApplication.translate("DockWidget", u"Disabled", None))
#if QT_CONFIG(tooltip)
        self.verticalScrollBarDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.verticalScrollBarDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.verticalScrollBarDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_21.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_21.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_21.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_21.setText(QCoreApplication.translate("DockWidget", u"Dial", None))
#if QT_CONFIG(tooltip)
        self.verticalScrollBar.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.verticalScrollBar.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.verticalScrollBar.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.horizontalScrollBar.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.horizontalScrollBar.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.horizontalScrollBar.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.comboBox.setItemText(0, QCoreApplication.translate("DockWidget", u"ComboBoxNotEditable", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("DockWidget", u"Option 1 No Icon", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("DockWidget", u"Option 2 No Icon", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("DockWidget", u"Option 1 With Icon", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("DockWidget", u"Option 2 With Icon", None))

#if QT_CONFIG(tooltip)
        self.comboBox.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.comboBox.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.comboBox.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.label_22.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_22.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_22.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_22.setText(QCoreApplication.translate("DockWidget", u"HorizontalScroolBar", None))
        self.label.setText(QCoreApplication.translate("DockWidget", u"Enabled", None))
#if QT_CONFIG(tooltip)
        self.label_50.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_50.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_50.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_50.setText(QCoreApplication.translate("DockWidget", u"Inside DockWidget", None))
#if QT_CONFIG(tooltip)
        self.label_11.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_11.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_11.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.label_11.setText(QCoreApplication.translate("DockWidget", u"ComboBox", None))
#if QT_CONFIG(tooltip)
        self.dialDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dialDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.dialDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.verticalSliderDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.verticalSliderDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.verticalSliderDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
        self.comboBoxDis.setItemText(0, QCoreApplication.translate("DockWidget", u"ComboBoxNotEditable", None))
        self.comboBoxDis.setItemText(1, QCoreApplication.translate("DockWidget", u"ComboBox B", None))
        self.comboBoxDis.setItemText(2, QCoreApplication.translate("DockWidget", u"ComboBox C", None))

#if QT_CONFIG(tooltip)
        self.comboBoxDis.setToolTip(QCoreApplication.translate("DockWidget", u"This is a tool tip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.comboBoxDis.setStatusTip(QCoreApplication.translate("DockWidget", u"This is a status tip", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.comboBoxDis.setWhatsThis(QCoreApplication.translate("DockWidget", u"This is \"what is this\"", None))
#endif // QT_CONFIG(whatsthis)
    # retranslateUi

