# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mw_menus.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import style_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1226, 719)
        self.actionActionA = QAction(MainWindow)
        self.actionActionA.setObjectName(u"actionActionA")
        self.actionActionSubA = QAction(MainWindow)
        self.actionActionSubA.setObjectName(u"actionActionSubA")
        self.actionActionSubB = QAction(MainWindow)
        self.actionActionSubB.setObjectName(u"actionActionSubB")
        self.actionActionDelayedA = QAction(MainWindow)
        self.actionActionDelayedA.setObjectName(u"actionActionDelayedA")
        self.actionActionDelayedSubA = QAction(MainWindow)
        self.actionActionDelayedSubA.setObjectName(u"actionActionDelayedSubA")
        self.actionActionCheckableA = QAction(MainWindow)
        self.actionActionCheckableA.setObjectName(u"actionActionCheckableA")
        self.actionActionCheckableA.setCheckable(True)
        self.actionActionCheckableA.setEnabled(True)
        self.actionActionCheckableSubAChecked = QAction(MainWindow)
        self.actionActionCheckableSubAChecked.setObjectName(u"actionActionCheckableSubAChecked")
        self.actionActionCheckableSubAChecked.setCheckable(True)
        self.actionActionCheckableSubAChecked.setChecked(True)
        self.actionActionCheckableSubAUnchecked = QAction(MainWindow)
        self.actionActionCheckableSubAUnchecked.setObjectName(u"actionActionCheckableSubAUnchecked")
        self.actionActionCheckableSubAUnchecked.setCheckable(True)
        self.actionNewB = QAction(MainWindow)
        self.actionNewB.setObjectName(u"actionNewB")
        self.actionNewC = QAction(MainWindow)
        self.actionNewC.setObjectName(u"actionNewC")
        self.actionNewD = QAction(MainWindow)
        self.actionNewD.setObjectName(u"actionNewD")
        self.actionNewE = QAction(MainWindow)
        self.actionNewE.setObjectName(u"actionNewE")
        self.actionActionIconADis = QAction(MainWindow)
        self.actionActionIconADis.setObjectName(u"actionActionIconADis")
        self.actionActionIconADis.setEnabled(False)
        icon = QIcon()
        icon.addFile(u":/qss_icons/dark/rc/window_undock_focus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionActionIconADis.setIcon(icon)
        self.actionActionIconB = QAction(MainWindow)
        self.actionActionIconB.setObjectName(u"actionActionIconB")
        self.actionActionIconB.setEnabled(True)
        icon1 = QIcon()
        icon1.addFile(u":/qss_icons/dark/rc/window_close_focus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionActionIconB.setIcon(icon1)
        self.actionActionIconC = QAction(MainWindow)
        self.actionActionIconC.setObjectName(u"actionActionIconC")
        icon2 = QIcon()
        icon2.addFile(u":/qss_icons/dark/rc/window_grip_focus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionActionIconC.setIcon(icon2)
        self.actionActionDis = QAction(MainWindow)
        self.actionActionDis.setObjectName(u"actionActionDis")
        self.actionActionDis.setEnabled(False)
        self.actionActionCheckableCheckedDis = QAction(MainWindow)
        self.actionActionCheckableCheckedDis.setObjectName(u"actionActionCheckableCheckedDis")
        self.actionActionCheckableCheckedDis.setCheckable(True)
        self.actionActionCheckableCheckedDis.setChecked(True)
        self.actionActionCheckableCheckedDis.setEnabled(False)
        self.actionActionCheckableUncheckedDis = QAction(MainWindow)
        self.actionActionCheckableUncheckedDis.setObjectName(u"actionActionCheckableUncheckedDis")
        self.actionActionCheckableUncheckedDis.setCheckable(True)
        self.actionActionCheckableUncheckedDis.setEnabled(False)
        self.actionActionTranspIcon = QAction(MainWindow)
        self.actionActionTranspIcon.setObjectName(u"actionActionTranspIcon")
        icon3 = QIcon()
        icon3.addFile(u":/qss_icons/dark/rc/transparent.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionActionTranspIcon.setIcon(icon3)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_7 = QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.label_71 = QLabel(self.centralwidget)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setAlignment(Qt.AlignCenter)

        self.gridLayout_7.addWidget(self.label_71, 3, 0, 1, 1)

        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.gridLayout = QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.groupBox_2)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.gridLayout_4 = QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.gridLayout_5 = QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)

        self.lineEdit = QLineEdit(self.groupBox_3)
        self.lineEdit.setObjectName(u"lineEdit")

        self.gridLayout_5.addWidget(self.lineEdit, 0, 1, 1, 1)

        self.frame = QFrame(self.groupBox_3)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.formLayout = QFormLayout(self.frame)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.label_3)

        self.lineEdit_2 = QLineEdit(self.frame)
        self.lineEdit_2.setObjectName(u"lineEdit_2")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.lineEdit_2)

        self.listWidget_2 = QListWidget(self.frame)
        QListWidgetItem(self.listWidget_2)
        self.listWidget_2.setObjectName(u"listWidget_2")

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.listWidget_2)


        self.gridLayout_5.addWidget(self.frame, 2, 0, 1, 2)

        self.listWidget = QListWidget(self.groupBox_3)
        QListWidgetItem(self.listWidget)
        self.listWidget.setObjectName(u"listWidget")

        self.gridLayout_5.addWidget(self.listWidget, 1, 1, 1, 1)


        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayout_6 = QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.gridLayout_3 = QGridLayout(self.tab_12)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.tabWidget.addTab(self.tab_12, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)


        self.gridLayout_7.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.gridLayout_2 = QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setLineWidth(0)
        self.label.setTextFormat(Qt.RichText)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(True)
        self.label.setTextInteractionFlags(Qt.TextBrowserInteraction)

        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)


        self.gridLayout_7.addWidget(self.groupBox, 1, 0, 1, 1)

        self.groupBoxDialogs = QGroupBox(self.centralwidget)
        self.groupBoxDialogs.setObjectName(u"groupBoxDialogs")
        self.gridLayout_8 = QGridLayout(self.groupBoxDialogs)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.toolButtonFileDialog = QToolButton(self.groupBoxDialogs)
        self.toolButtonFileDialog.setObjectName(u"toolButtonFileDialog")

        self.gridLayout_8.addWidget(self.toolButtonFileDialog, 1, 0, 1, 1)

        self.toolButtonFileDialogStatic = QToolButton(self.groupBoxDialogs)
        self.toolButtonFileDialogStatic.setObjectName(u"toolButtonFileDialogStatic")

        self.gridLayout_8.addWidget(self.toolButtonFileDialogStatic, 1, 1, 1, 1)

        self.toolButtonMessageBox = QToolButton(self.groupBoxDialogs)
        self.toolButtonMessageBox.setObjectName(u"toolButtonMessageBox")

        self.gridLayout_8.addWidget(self.toolButtonMessageBox, 1, 2, 1, 1)

        self.toolButtonMessageBoxStatic = QToolButton(self.groupBoxDialogs)
        self.toolButtonMessageBoxStatic.setObjectName(u"toolButtonMessageBoxStatic")

        self.gridLayout_8.addWidget(self.toolButtonMessageBoxStatic, 1, 3, 1, 1)

        self.toolButtonFontDialog = QToolButton(self.groupBoxDialogs)
        self.toolButtonFontDialog.setObjectName(u"toolButtonFontDialog")

        self.gridLayout_8.addWidget(self.toolButtonFontDialog, 2, 0, 1, 1)

        self.toolButtonColorDialog = QToolButton(self.groupBoxDialogs)
        self.toolButtonColorDialog.setObjectName(u"toolButtonColorDialog")

        self.gridLayout_8.addWidget(self.toolButtonColorDialog, 2, 1, 1, 1)

        self.toolButtonInputDialog = QToolButton(self.groupBoxDialogs)
        self.toolButtonInputDialog.setObjectName(u"toolButtonInputDialog")

        self.gridLayout_8.addWidget(self.toolButtonInputDialog, 2, 2, 1, 1)

        self.toolButtonProgressDialog = QToolButton(self.groupBoxDialogs)
        self.toolButtonProgressDialog.setObjectName(u"toolButtonProgressDialog")

        self.gridLayout_8.addWidget(self.toolButtonProgressDialog, 2, 3, 1, 1)

        self.label_5 = QLabel(self.groupBoxDialogs)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 4)


        self.gridLayout_7.addWidget(self.groupBoxDialogs, 2, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1226, 23))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        self.menuMenuSub = QMenu(self.menuMenu)
        self.menuMenuSub.setObjectName(u"menuMenuSub")
        self.menuMenuDelayed = QMenu(self.menubar)
        self.menuMenuDelayed.setObjectName(u"menuMenuDelayed")
        self.menuMenuSubDelayed = QMenu(self.menuMenuDelayed)
        self.menuMenuSubDelayed.setObjectName(u"menuMenuSubDelayed")
        self.menuMenuCheckale = QMenu(self.menubar)
        self.menuMenuCheckale.setObjectName(u"menuMenuCheckale")
        self.menuNew = QMenu(self.menuMenuCheckale)
        self.menuNew.setObjectName(u"menuNew")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuMenuActionDis = QMenu(self.menubar)
        self.menuMenuActionDis.setObjectName(u"menuMenuActionDis")
        self.menuMenuActionDis.setEnabled(True)
        self.menuMenuDisabled = QMenu(self.menubar)
        self.menuMenuDisabled.setObjectName(u"menuMenuDisabled")
        self.menuMenuDisabled.setEnabled(False)
        self.menuMenuTranspIcon = QMenu(self.menubar)
        self.menuMenuTranspIcon.setObjectName(u"menuMenuTranspIcon")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setEnabled(True)
        self.toolBar.setIconSize(QSize(16, 16))
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        self.toolBarDelayed = QToolBar(MainWindow)
        self.toolBarDelayed.setObjectName(u"toolBarDelayed")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarDelayed)
        self.toolBarCheckable = QToolBar(MainWindow)
        self.toolBarCheckable.setObjectName(u"toolBarCheckable")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarCheckable)
        MainWindow.insertToolBarBreak(self.toolBarCheckable)
        self.toolBarActionDis = QToolBar(MainWindow)
        self.toolBarActionDis.setObjectName(u"toolBarActionDis")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarActionDis)
        self.toolBarMenus = QToolBar(MainWindow)
        self.toolBarMenus.setObjectName(u"toolBarMenus")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarMenus)
        self.toolBarDis = QToolBar(MainWindow)
        self.toolBarDis.setObjectName(u"toolBarDis")
        self.toolBarDis.setEnabled(False)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarDis)
        QWidget.setTabOrder(self.lineEdit, self.tabWidget)
        QWidget.setTabOrder(self.tabWidget, self.lineEdit_2)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuMenuDelayed.menuAction())
        self.menubar.addAction(self.menuMenuCheckale.menuAction())
        self.menubar.addAction(self.menuMenuActionDis.menuAction())
        self.menubar.addAction(self.menuMenuDisabled.menuAction())
        self.menubar.addAction(self.menuMenuTranspIcon.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuMenu.addAction(self.actionActionA)
        self.menuMenu.addAction(self.menuMenuSub.menuAction())
        self.menuMenu.addAction(self.actionActionIconADis)
        self.menuMenu.addAction(self.actionActionIconB)
        self.menuMenu.addAction(self.actionActionIconC)
        self.menuMenuSub.addAction(self.actionActionSubA)
        self.menuMenuSub.addAction(self.actionActionSubB)
        self.menuMenuDelayed.addAction(self.actionActionDelayedA)
        self.menuMenuDelayed.addAction(self.actionActionCheckableA)
        self.menuMenuDelayed.addAction(self.menuMenuSubDelayed.menuAction())
        self.menuMenuSubDelayed.addAction(self.actionActionDelayedSubA)
        self.menuMenuCheckale.addAction(self.actionActionCheckableA)
        self.menuMenuCheckale.addAction(self.actionActionIconADis)
        self.menuMenuCheckale.addAction(self.actionActionIconB)
        self.menuMenuCheckale.addAction(self.actionActionIconC)
        self.menuMenuCheckale.addSeparator()
        self.menuMenuCheckale.addAction(self.menuNew.menuAction())
        self.menuNew.addSeparator()
        self.menuNew.addAction(self.actionNewB)
        self.menuNew.addAction(self.actionNewD)
        self.menuNew.addAction(self.actionNewC)
        self.menuNew.addSeparator()
        self.menuNew.addAction(self.actionNewE)
        self.menuMenuActionDis.addAction(self.actionActionDis)
        self.menuMenuActionDis.addAction(self.actionActionCheckableCheckedDis)
        self.menuMenuActionDis.addAction(self.actionActionCheckableUncheckedDis)
        self.menuMenuActionDis.addAction(self.actionActionIconADis)
        self.menuMenuActionDis.addAction(self.actionActionIconB)
        self.menuMenuActionDis.addAction(self.actionActionIconC)
        self.menuMenuTranspIcon.addAction(self.actionActionCheckableA)
        self.menuMenuTranspIcon.addAction(self.actionActionTranspIcon)
        self.toolBar.addAction(self.actionActionA)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionActionSubA)
        self.toolBar.addAction(self.actionActionSubB)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionActionIconADis)
        self.toolBar.addAction(self.actionActionIconB)
        self.toolBar.addAction(self.actionActionIconC)
        self.toolBarDelayed.addAction(self.actionActionDelayedA)
        self.toolBarDelayed.addSeparator()
        self.toolBarDelayed.addAction(self.actionActionDelayedSubA)
        self.toolBarCheckable.addAction(self.actionActionCheckableA)
        self.toolBarCheckable.addSeparator()
        self.toolBarCheckable.addAction(self.actionActionCheckableSubAChecked)
        self.toolBarCheckable.addAction(self.actionActionCheckableSubAUnchecked)
        self.toolBarActionDis.addAction(self.actionActionDis)
        self.toolBarActionDis.addAction(self.actionActionCheckableCheckedDis)
        self.toolBarActionDis.addAction(self.actionActionCheckableUncheckedDis)
        self.toolBarDis.addAction(self.actionActionA)
        self.toolBarDis.addAction(self.actionActionSubA)
        self.toolBarDis.addAction(self.actionActionCheckableCheckedDis)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionActionA.setText(QCoreApplication.translate("MainWindow", u"Action A", None))
        self.actionActionSubA.setText(QCoreApplication.translate("MainWindow", u"Action A Sub", None))
#if QT_CONFIG(tooltip)
        self.actionActionSubA.setToolTip(QCoreApplication.translate("MainWindow", u"Action A Sub", None))
#endif // QT_CONFIG(tooltip)
        self.actionActionSubB.setText(QCoreApplication.translate("MainWindow", u"Action B Sub", None))
        self.actionActionDelayedA.setText(QCoreApplication.translate("MainWindow", u"Action Delayed A", None))
#if QT_CONFIG(tooltip)
        self.actionActionDelayedA.setToolTip(QCoreApplication.translate("MainWindow", u"Action Delayed A", None))
#endif // QT_CONFIG(tooltip)
        self.actionActionDelayedSubA.setText(QCoreApplication.translate("MainWindow", u"Action Delayed Sub A", None))
#if QT_CONFIG(tooltip)
        self.actionActionDelayedSubA.setToolTip(QCoreApplication.translate("MainWindow", u"Action Delayed Sub A", None))
#endif // QT_CONFIG(tooltip)
        self.actionActionCheckableA.setText(QCoreApplication.translate("MainWindow", u"Action Checkable A", None))
#if QT_CONFIG(tooltip)
        self.actionActionCheckableA.setToolTip(QCoreApplication.translate("MainWindow", u"Action Checkable A", None))
#endif // QT_CONFIG(tooltip)
        self.actionActionCheckableSubAChecked.setText(QCoreApplication.translate("MainWindow", u"Action Checkable Sub A Checked", None))
#if QT_CONFIG(tooltip)
        self.actionActionCheckableSubAChecked.setToolTip(QCoreApplication.translate("MainWindow", u"Action Checkable Sub A Checked", None))
#endif // QT_CONFIG(tooltip)
        self.actionActionCheckableSubAUnchecked.setText(QCoreApplication.translate("MainWindow", u"Action Checkable Sub A Unchecked", None))
#if QT_CONFIG(tooltip)
        self.actionActionCheckableSubAUnchecked.setToolTip(QCoreApplication.translate("MainWindow", u"Action Checkable Sub A Unchecked", None))
#endif // QT_CONFIG(tooltip)
        self.actionNewB.setText(QCoreApplication.translate("MainWindow", u"New B", None))
        self.actionNewC.setText(QCoreApplication.translate("MainWindow", u"New C", None))
        self.actionNewD.setText(QCoreApplication.translate("MainWindow", u"New D", None))
        self.actionNewE.setText(QCoreApplication.translate("MainWindow", u"New E", None))
        self.actionActionIconADis.setText(QCoreApplication.translate("MainWindow", u"Action Icon A", None))
        self.actionActionIconB.setText(QCoreApplication.translate("MainWindow", u"Action Icon B", None))
#if QT_CONFIG(tooltip)
        self.actionActionIconB.setToolTip(QCoreApplication.translate("MainWindow", u"Action Icon B", None))
#endif // QT_CONFIG(tooltip)
        self.actionActionIconC.setText(QCoreApplication.translate("MainWindow", u"Action Icon C", None))
        self.actionActionDis.setText(QCoreApplication.translate("MainWindow", u"Action Disabled", None))
#if QT_CONFIG(tooltip)
        self.actionActionDis.setToolTip(QCoreApplication.translate("MainWindow", u"Action Disabled", None))
#endif // QT_CONFIG(tooltip)
        self.actionActionCheckableCheckedDis.setText(QCoreApplication.translate("MainWindow", u"Action Checkable Checked Disabled", None))
#if QT_CONFIG(tooltip)
        self.actionActionCheckableCheckedDis.setToolTip(QCoreApplication.translate("MainWindow", u"Action Checkable Checked Disabled", None))
#endif // QT_CONFIG(tooltip)
        self.actionActionCheckableUncheckedDis.setText(QCoreApplication.translate("MainWindow", u"Action Checkable Unchecked Disabled", None))
#if QT_CONFIG(tooltip)
        self.actionActionCheckableUncheckedDis.setToolTip(QCoreApplication.translate("MainWindow", u"Action Checkable Unchecked Disabled", None))
#endif // QT_CONFIG(tooltip)
        self.actionActionTranspIcon.setText(QCoreApplication.translate("MainWindow", u"Action Transp. Icon", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"Inside Central Widget", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Issue #115 - Tabs scroller buttons", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Issue #123 - Missing borders", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"Inside tab, outside frame", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lineEdit_2.setText(QCoreApplication.translate("MainWindow", u"Inside tab and frame", None))

        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        ___qlistwidgetitem = self.listWidget_2.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"ListWidget", None));
        self.listWidget_2.setSortingEnabled(__sortingEnabled)


        __sortingEnabled1 = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        ___qlistwidgetitem1 = self.listWidget.item(0)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"ListWidget", None));
        self.listWidget.setSortingEnabled(__sortingEnabled1)

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Tab 3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Colored tab text", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Page", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Page", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Page", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Page", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"Page", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"Page", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"Page", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"Page", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Issue #112 - Hyperlinks color", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><a href=\"https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/112\"><span style=\" font-size:10pt; text-decoration: underline; color:#0000ff;\">Hyperlink Example</span></a></p><p align=\"center\"><span style=\" font-size:10pt; color:#7d7d7d;\">CSS for the documents (RichText) is not the same as the application. We cannot change the internal content CSS, e.g., hyperlinks. We suggest you use the middle tons (0-255, use 125), so this works for both white and dark theme (this color). The original color is the blue link on top.</span></p><p align=\"center\"><br/></p></body></html>", None))
        self.groupBoxDialogs.setTitle(QCoreApplication.translate("MainWindow", u"Dialogs", None))
        self.toolButtonFileDialog.setText(QCoreApplication.translate("MainWindow", u"FileDialog", None))
        self.toolButtonFileDialogStatic.setText(QCoreApplication.translate("MainWindow", u"FileDialogStatic", None))
        self.toolButtonMessageBox.setText(QCoreApplication.translate("MainWindow", u"MessageBox", None))
        self.toolButtonMessageBoxStatic.setText(QCoreApplication.translate("MainWindow", u"MessageBoxStatic", None))
        self.toolButtonFontDialog.setText(QCoreApplication.translate("MainWindow", u"FontDialog", None))
        self.toolButtonColorDialog.setText(QCoreApplication.translate("MainWindow", u"ColorDialog", None))
        self.toolButtonInputDialog.setText(QCoreApplication.translate("MainWindow", u"InputDialog", None))
        self.toolButtonProgressDialog.setText(QCoreApplication.translate("MainWindow", u"ProgressDialog", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Click to open the dialogs.", None))
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.menuMenuSub.setTitle(QCoreApplication.translate("MainWindow", u"Menu Sub", None))
        self.menuMenuDelayed.setTitle(QCoreApplication.translate("MainWindow", u"Menu Delayed", None))
        self.menuMenuSubDelayed.setTitle(QCoreApplication.translate("MainWindow", u"Menu Sub Delayed", None))
        self.menuMenuCheckale.setTitle(QCoreApplication.translate("MainWindow", u"Menu Checkable", None))
        self.menuNew.setTitle(QCoreApplication.translate("MainWindow", u"New", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"About QDarkStyle", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuMenuActionDis.setTitle(QCoreApplication.translate("MainWindow", u"Menu Action Disabled", None))
        self.menuMenuDisabled.setTitle(QCoreApplication.translate("MainWindow", u"Menu Disabled", None))
        self.menuMenuTranspIcon.setTitle(QCoreApplication.translate("MainWindow", u"Menu Transp. Icon", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tool bar actions", None))
#if QT_CONFIG(tooltip)
        self.toolBar.setToolTip(QCoreApplication.translate("MainWindow", u"Tool bar actions", None))
#endif // QT_CONFIG(tooltip)
        self.toolBarDelayed.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tool bar actions delayed", None))
#if QT_CONFIG(tooltip)
        self.toolBarDelayed.setToolTip(QCoreApplication.translate("MainWindow", u"Tool bar actions delayed", None))
#endif // QT_CONFIG(tooltip)
        self.toolBarCheckable.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tool bar action checkable", None))
#if QT_CONFIG(tooltip)
        self.toolBarCheckable.setToolTip(QCoreApplication.translate("MainWindow", u"Toolbar actions checkable", None))
#endif // QT_CONFIG(tooltip)
        self.toolBarActionDis.setWindowTitle(QCoreApplication.translate("MainWindow", u"Toolbar with actions disabled", None))
#if QT_CONFIG(tooltip)
        self.toolBarActionDis.setToolTip(QCoreApplication.translate("MainWindow", u"Toolbar with actions disabled", None))
#endif // QT_CONFIG(tooltip)
        self.toolBarMenus.setWindowTitle(QCoreApplication.translate("MainWindow", u"Toolbar with menu", None))
#if QT_CONFIG(tooltip)
        self.toolBarMenus.setToolTip(QCoreApplication.translate("MainWindow", u"Toolbar with menu", None))
#endif // QT_CONFIG(tooltip)
        self.toolBarDis.setWindowTitle(QCoreApplication.translate("MainWindow", u"Toolbar disabled", None))
#if QT_CONFIG(tooltip)
        self.toolBarDis.setToolTip(QCoreApplication.translate("MainWindow", u"Toolbar disabled", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

